name: axe
on: [push]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm start & npx wait-on 127.0.0.1:4000
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe 127.0.0.1:4000 --exit
